CREATE TABLE IF NOT EXISTS Accounts (
    AccountID SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(60) NOT NULL,
    xp INT NOT NULL DEFAULT 0,
    pfp VARCHAR(300),
    CurDate DATE,
    Quest1 INT NOT NULL DEFAULT 0,
    Quest2 INT NOT NULL DEFAULT 0,
    Quest3 INT NOT NULL DEFAULT 0,
    Q1Complete BOOLEAN NOT NULL DEFAULT FALSE,
    Q2Complete BOOLEAN NOT NULL DEFAULT FALSE,
    Q3Complete BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS AccountFriends (
    AccountID INT NOT NULL,
    FriendID INT NOT NULL,
    Pending BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccountID, FriendID),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID) ON DELETE CASCADE,
    FOREIGN KEY (FriendID) REFERENCES Accounts(AccountID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Exercises (
    ExerciseID SERIAL PRIMARY KEY,
    Date DATE NOT NULL,
    ExerciseName VARCHAR(50) NOT NULL,
    ExerciseXP INT NOT NULL,
    TimeQuant BOOLEAN NOT NULL,
    Amount INT NOT NULL
);

CREATE TABLE IF NOT EXISTS UserExercises (
    AccountID INT NOT NULL,
    ExerciseID INT NOT NULL,
    PRIMARY KEY (AccountID, ExerciseID),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID) ON DELETE CASCADE,
    FOREIGN KEY (ExerciseID) REFERENCES Exercises(ExerciseID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Goals (
    GoalID SERIAL PRIMARY KEY,
    AccountID INT NOT NULL,
    Description VARCHAR(500) NOT NULL,
    Deadline DATE NOT NULL,
    Completion BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Boss (
    BossID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    HP INT NOT NULL,
    MaxHP INT NOT NULL,
    Pic VARCHAR(300),
    RewardXP INT NOT NULL,
    Completion BOOLEAN NOT NULL DEFAULT FALSE,
    Deadline DATE NOT NULL
);
